### PR TITLE
Headless fix

### PR DESCRIPTION
**Pull request by macumber**
This includes my fixes, I do not know why the commit history is so huge

### CODE REVIEW

**Comment by macumber** [comment]
These are the only real commits:

https://github.com/NREL/Radiance/pull/13/commits/325b8e4236b3d31387fbe34f5727d746ebe4e8b5
https://github.com/NREL/Radiance/pull/13/commits/1d02ac95f28d27df85417636a2fd52fa4705dad7
https://github.com/NREL/Radiance/pull/13/commits/c386b557cce309ef5a825b5835cc1216f8fe1f4e
https://github.com/NREL/Radiance/pull/13/commits/abca2f721290878bf68d2b7d28899e79575e141f

**Comment by macumber** [comment]
@rpg777 I'm not sure the best way to get these into combined

@axelstudios FYI

**Comment by rpg777** [comment]
yeah, I got it. I just send Greg patches. THanks for fixing this!!

**Comment by rpg777** [comment]
The long commit history is because you are trying to merge all this into master, which we don't use as the, uh, master here. =/

**Pull request closed without merging**
